name: todolist
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5

  provider: ^6.0.3
  modal_progress_hud_nsn: ^0.3.0
  jiffy: ^5.0.0
  get_storage: ^2.0.3
  after_layout: ^1.2.0
  checkbox_grouped: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  flutter_app_name: ^0.1.0

flutter_app_name:
  name: "TodoMe "

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
